### PR TITLE
Fix Multi Board Bar issue + Add performance Optimization

### LINKED ISSUE #7: Extra board gets added when clicked on the existing board.
When clicking on the first board which has been added to the multi-page bar an extra board gets created.

bug

### PR DESCRIPTION
**Pull request by Aswal-Ashutosh**
- [x] Added default board in the beginning to the multi-board bar.
- [x] Fixed the bug creating extra board while switching between boards.
- [x] Improved performance by removing the function **showPreview** which is taking O(N) time to refresh the list.

Resolves #7

### CODE REVIEW

**Review by tanmayVaish — CHANGES_REQUESTED** [review]
You have done a remarkable job, but you have created a small issue. 

**Issue:** Background color of the preview images in the multi-board section are not changing when we are changing background color of the active board.

**Preview of the issue:**

_First one is yours_

https://user-images.githubusercontent.com/55585498/135769536-b3569aa5-578c-48df-8c52-6c0a5689c8bd.mp4


Please look into it!! Thank you!

**Comment by Aswal-Ashutosh** [comment]
> You have done a remarkable job, but you have created a small issue.
> 
> **Issue:** Background color of the preview images in the multi-board section are not changing when we are changing background color of the active board.
> 
> **Preview of the issue:**
> 
> _First one is yours_
> 
>  Untitled.design.mp4 
> Please look into it!! Thank you!

**Fixed**

**Review by tanmayVaish — APPROVED** [review]
Thanks bro! You did great. Approving your Pull Request!

**Comment by Aswal-Ashutosh** [comment]
> Thanks bro! You did great. Approving your Pull Request!

I will suggest you not change the background color of all boards, instead change the background color of the currently selected board only.

**Pull request merged**
